sudo: false
language: node_js
node_js:
  - '8'
install:
  - rm -rf node_modules
  - npm i npminstall && npminstall
script:
  - npm run docs:build
  - $(npm bin)/macaca-ecosystem push --cwd ./docs_dist --branch gh-pages
  - npm run lint
  - npm run cov
after_script:
  - npminstall codecov && codecov
